from typing import Protocol, Any

class IActiveTradeManager(Protocol):
    def add_trade(self, trade_no: int, order_id: str) -> None: ...
    def update(self, order_id: str, **kwargs) -> None: ...
    def close_trade(self, order_id: str) -> None: ...
    def get_active(self) -> Any | None: ...
    def has_active(self) -> bool: ...
    def mark_trailing_hit(self, order_id: str, level_idx: int) -> None: ...